- id: witech-gen-addon-readme
  name: Generate addons README files from fragments
  always_run: true
  entry: witech-gen-addon-readme
  language: python
  pass_filenames: false

- id: witech-gen-addons-table
  name: Generate addons table in README
  always_run: true
  entry: witech-gen-addons-table
  language: python
  pass_filenames: false

- id: witech-gen-addon-icon
  name: Generate addons icons
  always_run: true
  entry: witech-gen-addon-icon
  language: python
  pass_filenames: false

- id: witech-update-pre-commit-excluded-addons
  name: Update pre-commit excluded addons
  entry: witech-update-pre-commit-excluded-addons
  pass_filenames: false
  language: python
  always_run: true

- id: witech-fix-manifest-website
  name: Fix the manifest website key
  entry: witech-fix-manifest-website
  pass_filenames: false
  language: python
  files: (__manifest__\.py|__openerp__\.py|__terp__\.py)$

- id: witech-gen-external-dependencies
  name: Generate requirements.txt for an addons directory
  entry: witech-gen-external-dependencies
  language: python
  pass_filenames: false
  files: (__manifest__\.py|__openerp__\.py|__terp__\.py|setup\.py|pyproject\.toml)$
